//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessUser
    {
        public int AccessID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Create { get; set; }
        public Nullable<int> TabId { get; set; }
    }
}
