//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTab
    {
        public int TabId { get; set; }
        public string TabName { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
